routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('debug', 'DebugController@debug');

// route untuk login
Route::get('login', [ 'as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', [ 'as' => '', 'uses' => 'Auth\LoginController@login']);
Route::post('logout', [ 'as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

// route for programatically employee login to system
Route::get('a/{personnel_no}/{email}', 'Auth\LoginController@programaticallyEmployeeLogin')
    ->name('login.a');

// route for programatically secretary login to system
Route::get('b/{email}', 'Auth\LoginController@programaticallySecretaryLogin')
    ->name('login.b');

// route untuk user yang belum di set Role-nya
Route::get('noRole', 'HomeController@noRole')->name('noRole');

Route::get('ski/{id}/kode/{klp}/{bulan}/{tahun}/{key}', 'SkiController@kode')->name('ski.kode');

app/Models/Ski.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\ReceiveStage;
use App\Traits\OfLoggedUser;
use App\Models\Employee;
use App\Models\Secretary;

class Ski extends Model
{
    use ReceiveStage,OfLoggedUser;

    public function user()
    {
        // many-to-one relationship dengan User
        return $this->belongsTo('App\User', 'personnel_no', 'personnel_no');
    }

    public function employee()
    {
        // many-to-one relationship dengan Employee
        return $this->belongsTo('App\Models\Employee', 'personnel_no', 'personnel_no');
    } 

    public function stage()
    {
        // many-to-one relationship dengan Stage
        return $this->belongsTo('App\Models\Stage')->withDefault();
    }

    public function skiApproval()
    {
        // one-to-many relationship dengan SkiApproval
        return $this->hasMany('App\Models\SkiApproval');
    }

    public function skiDetail()
    {
        // one-to-many relationship dengan SkiDetail
        return $this->hasMany('App\Models\SkiDetail');
    }

    public function secretary()
    {
        return $this->belongsTo('App\Models\Secretary');
    }
    
    public function getPlainIdAttribute()
    {
        return 'ski-' . $this->id;
    }
    public function getCreatedByAttribute()
    {
        if($this->dirnik !== null){
            $dirnik = Employee::find($this->dirnik);
        }else{
            $dirnik = Secretary::find($this->secretary_id);
        }
        
        return $dirnik->name;
    }
    public function getFirstApprovalAttribute()
    {
        // mencari approval dengan sequence 1
        return $this->skiApproval()->where('sequence', 1)->first();
    }

    public function getSecondApprovalAttribute()
    {
        // mencari approval dengan sequence 2
        return $this->skiApproval()->where('sequence', 2)->first();
    }

    public function scopefoundMonth($query)
    {
        $month = $query->select('month')->orderBy('month', 'ASC')->groupBy( 'month' )->get();
        $arr = [];
        foreach ($month as $key => $value) {
            $arr[$value->month] = date("F", mktime(0, 0, 0, $value->month, 10));
        }
        return collect($arr);
    }

    public function scopefoundYear($query)
    {
        $query->select('year')->orderBy('year', 'desc')->groupBy( 'year' );          
    }
}

app/Http/Controllers/Dashboard/Employee/OvertimeController.php
<?php

namespace App\Http\Controllers\Dashboard\Employee;

use Illuminate\Http\Request;
use App\Models\AttendanceQuota as Overtime;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Models\Employee;

class OvertimeController extends DashboardController
{
    protected $ofmonths, $ofyears, $ofboss, $ofsubordinatesboss, $ofsubordinates;

    protected function subBoss(Request $request)
    {
        // bawahan yang memiliki bawahan? haha
        // option value untuk select bawahan dari orang yang sedang login
        $this->ofsubordinatesboss = $this->user->closestStructuralSubordinates();
        // masukkan diri sendiri pada elemen terkahir
        $this->ofsubordinatesboss->push($this->user);

        // value untuk select filter & parameter query
        // cari bawahan dari atasanya yang telah dipilih
        if ($request->has('ofboss')) {
            $this->ofboss = Employee::find($request->ofboss);
        } else {
            $this->ofboss = $this->ofsubordinatesboss->first();
        }

        // cari bawahan dari ofboss
        $this->ofsubordinates = $this->ofboss->subordinates();
    }

    public function filter(Request $request)
    {
        // mencari bulan-bulan yang valid untuk select filter
        $months = collect();
        foreach (range(1, 12) as $m) {
            if ($m == intval(date('m'))) break;
            $months->push([
                'number' => $m,
                'name' => $this->monthNumToText($m),
            ]);
        }
        $this->ofmonths = $months->sortByDesc('number')->values();

        // mencari tahun-tahun yang valid untuk select filter
        $this->ofyears = Overtime::selectRaw('year(start_date) as year')
            ->whereIn('personnel_no', $this->subordinates)
            ->successOnly()
            ->groupBy('year')
            ->orderByRaw('year DESC')
            ->get();

        // inisialisasi bawahan dari atasan terpilih
        $this->subBoss($request);

        return response()
            ->json([
                'ofmonths' => $this->ofmonths,
                'ofyears' => $this->ofyears,
                'ofsubordinatesboss' => $this->ofsubordinatesboss,
            ]);
    }

    public function chart(Request $request)
    {
        // bulan dan tahun yang telah dipilih
        $ofmonth = $request->has('ofmonth') ?
            $request->ofmonth : (!is_null($this->ofmonths) ?
                sprintf('%02d', $this->ofmonths->first()->month) : date('m'));
        $ofyear = $request->has('ofyear') ?
            $request->ofyear : (!is_null($this->ofyears) ?
                $this->ofyears->first()->year : date('Y'));

        // inisialisasi bawahan dari atasan terpilih
        $this->subBoss($request);

        // mencari data lembur untuk bawahan dari atasan yang telah dipilih
        $overtimeChartData = Overtime::selectRaw(
            'CONCAT(attendance_quotas.personnel_no, " - ", employees.name) as label, ' .
                'SUM(TIMESTAMPDIFF(SECOND, start_date, end_date)/3600) AS value'
        )
            ->whereIn('attendance_quotas.personnel_no', $this->ofsubordinates->pluck('personnel_no'))
            ->leftJoin('employees', 'attendance_quotas.personnel_no', '=', 'employees.personnel_no')
            ->monthYearOf($ofmonth, $ofyear)
            ->successOnly()
            ->groupBy('attendance_quotas.personnel_no')
            ->orderByRaw('value DESC')
            ->get();

        $chartOptions = [
            "caption" => "Lembur Karyawan " . $this->ofboss->org_unit_name,
            "subcaption" => $this->monthNumToText($ofmonth) . ' ' . $ofyear,
            "xaxisname" => "Karyawan",
            "yaxisname" => "Total lembur (jam)",
        ];
        $dataSource = [
            "chart" => array_merge($chartOptions, $this->chartThemes),
            "data" => $overtimeChartData
        ];

        // kembalikan JSON
        return response()->json($dataSource);
    }
}

app/Http/Controllers/OvertimeController.php
<?php

namespace App\Http\Controllers;

use Session;
use Carbon\Carbon;
use Illuminate\Config;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Yajra\DataTables\Datatables;
use Yajra\DataTables\Html\Builder;
use App\Models\AttendanceQuota;
use App\Models\AttendanceQuotaType;
use App\Models\OvertimeReason;
use App\Http\Requests\StoreAttendanceQuotaRequest;

class OvertimeController extends Controller
{
    public function index(Request $request, Builder $htmlBuilder)
    {
        $allowed = Auth::user()
            ->employee
            ->allowedToSubmitSubordinateOvertime();

        if($allowed) {
            $lembur ="Daftar Lembur Bawahan Saya";
            $subordinates = Auth::user()
                ->employee
                ->foremanAndOperatorSubordinates();

            $overtimes = collect();
            foreach ($subordinates as $subordinate) {
                $overtimes = $overtimes->merge(
                    $subordinate->personnel_no
                );
            }
            
            $overtimes = AttendanceQuota::whereIn('personnel_no', $overtimes)
            ->with(['overtimeReason', 'stage'])
            ->orderBy('id','desc');
            
        } else {
            // ambil data cuti untuk user tersebut
            $lembur ="Daftar Lembur Saya";
            $overtimes = AttendanceQuota::ofLoggedUser()
            ->with(['overtimeReason', 'stage'])
            ->orderBy('id','desc');
        }

        // response untuk datatables attendanceQuota
        if ($request->ajax()) {

            return Datatables::of($overtimes)
                ->editColumn('summary', function ($overtime) {
                    // kolom summary menggunakan view _summary
                    return view('overtimes._summary', [ 
                        'summary' => $overtime,
                        'when' => $overtime->created_at->format('d/m') 
                    ]);
                })
                ->editColumn('approver', function ($overtime) {
                    // personnel_no dan name atasan
                        $views = '';
                        foreach ($overtime->attendanceQuotaApproval as $item) {
                            $views =  $views . view('layouts._personnel-no-with-name', [
                                'personnel_no' => $item->employee['personnel_no'],
                                'employee_name' => $item->employee['name'],
                            ]) . '<br />';
                        }
                    return $views;
                })
                ->setRowAttr([
                    // href untuk dipasang di setiap tr
                    'data-href' => function ($overtime) {
                        return route('overtimes.show', ['leaf' => $overtime->id]);
                    } 
                ])
                ->escapeColumns([0,1])
                ->make(true);
        }

        // disable paging, searching, details button but enable responsive
        $htmlBuilder->parameters([
            'paging' => true,
            'searching' => false,
            'responsive' => [ 'details' => false ],
            "columnDefs" => [ [ "width" => "60%", "targets" => 0 ] ]
        ]);

        $html = $htmlBuilder
            ->addColumn([
                'data' => 'summary',
                'name' => 'summary',
                'title' => 'Summary',
                'searchable' => false,
                'orderable' => false, 
                ])
            ->addColumn([
                'data' => 'approver',
                'name' => 'approver',
                'title' => 'Approver',
                'class' => 'desktop',
                'searchable' => false,
                'orderable' => false,
                ]);

        // tampilkan view index dengan tambahan script html DataTables
        return view('overtimes.index')->with(compact('html', 'overtimes','lembur'));
    }

    public function create()
    {
        // user yang dapat melakukan pengajuan lembur
        $user = Auth::user()->personnel_no;

        // alasan lembur
        $overtime_reason = OvertimeReason::all('id', 'text')
        ->mapWithKeys(function ($item) {
            return [$item['id'] => $item['text']];
        })
        ->all();

        // mengecek apakah boleh mengajukan overtime untuk bawahan
        $allowed = Auth::user()
            ->employee
            ->allowedToSubmitSubordinateOvertime();

        if ($allowed) {
            // route untuk menyimpan from employee
            $formRoute = route('overtimes.store');
            $pageContainer = 'layouts.employee._page-container';
            
            // menampilkan view create overtime secretary
            return view('overtimes.createas', 
                compact('overtime_reason','user','formRoute','pageContainer')
            );
        } else {

            Session::flash("flash_notification", [
                "level" => "danger",
                "message" => "Mohon maaf, Anda tidak dapat mengajukan lembur. " . 
                    "Silahkan hubungi Supervisor/Superintendent/Sekretaris Divisi " .
                    "untuk mengajukan lembur Anda."
            ]);
            // batalkan view create dan kembali ke parent
            return redirect()->route('overtimes.index'); 
        }
    }

    public function store(StoreAttendanceQuotaRequest $request)
    {
        // tampilkan pesan bahwa telah berhasil mengajukan cuti
        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Berhasil menyimpan pengajuan lembur.",
        ]);
        
        // start date
        $start_date = Carbon::createFromFormat('Y-m-d H:i', 
            $request->input('start_date') . ' ' . $request->input('from'));
        // menghitung end_date berdasarkan day_assignment
        switch ($request->input('day_assignment')) {
            case '=':
                $end_date = Carbon::create(
                    $start_date->year, 
                    $start_date->month,
                    $start_date->day,
                    substr($request->input('to'), 0, 2),
                    substr($request->input('to'), 3, 2),
                    0);
            break;
            case '>':
                $end_date = Carbon::create(
                    $start_date->year, 
                    $start_date->month,
                    $start_date->day,
                    substr($request->input('to'), 0, 2),
                    substr($request->input('to'), 3, 2),
                    0)
                    ->addDays(1);
            break;
        }

        // membuat pengajuan lembur dengan menambahkan data personnel_no
        $overtime = new AttendanceQuota();
        $overtime->personnel_no = $request->input('personnel_no');
        $overtime->start_date = $start_date;
        $overtime->end_date = $end_date;
        $overtime->attendance_quota_type_id = AttendanceQuotaType::suratPerintahLembur()->id;
        $overtime->overtime_reason_id = $request->input('overtime_reason_id');
        $overtime->dirnik = Auth::user()->personnel_no;
        $overtime->save();

        // kembali ke halaman index overtime
        return redirect()->route('overtimes.index');
    }

    public function show($id)
    {
        $overtime = AttendanceQuota::find($id)
            ->load(['attendanceQuotaType', 'stage', 'attendanceQuotaApproval']);

        $overtimeId = $overtime->id;
        
        return view('overtimes.show', compact('overtime', 'overtimeId'));
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/overtimes/_form.blade.php
  {{-- 
    Form Elements: personnel_no, start_date, day_assignment, from,
    to, overtime_reason, delegation (if have subordinates)
  --}}

<div class="col-lg-4">
  @include('layouts._flash')
  <div class="alert alert-success fade in">
      <i class="fa fa-paper-plane pull-left"></i>
      <p>Pastikan bahwa tanggal yang dipilih tidak terdapat hari libur kerja/nasional di dalam jadwal kerja Anda.</p>
      <br />
      <i class="fa fa-calendar pull-left"></i>
      <p>Silahkan isi tanggal pengajuan lembur Anda dengan memilih tanggal pada kalender.</p>
      <br />
      <i class="fa fa-clock-o pull-left"></i>
      <p>Silahkan isi keterangan apakah lembur selesai pada hari yang sama atau keesokan hari.</p>
      <br />
      <i class="fa fa-clock-o pull-left"></i>
      <p>Silahkan isi jam mulai dan berakhir lembur Anda dengan memilih jam pada icon <i class="fa fa-clock-o"></i>.</p>
      <br />
      <i class="fa fa-sliders pull-left"></i>
      <p>Silahkan isi jenis lembur Anda.</p>
      <br />
  </div>     
</div>

<!-- begin datepicker inline -->
<div class="col-lg-4">
  <h5 class="text-center">Pilih tanggal</h5>
  <div id="datepicker-inline" class="datepicker-range">
    <div></div>
  </div>
</div>
<!-- end datepicker inline -->

  <div class="col-lg-4">
    <!-- begin personnel_no field -->
    <div class="form-group{{ $errors->has('personnel_no') ? ' has-error' : '' }}">
      {!! Form::hidden('personnel_no', Auth::user()->employee()->first()->personnel_no, 
        ['class'=>'form-control', 'placeholder'=>'NIK', 'readonly'=>'true', 
          'id'=>'personnel_no'] ) !!}
      {!! $errors->first('personnel_no', '<p class="help-block">:message</p>') !!}
    </div>
    <!-- end personnel_no field -->

    <div class="row">
      <!-- begin start_date field -->
      <div class="col-xs-6">
        <div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
          {!! Form::label('start_date', 'Tanggal Mulai') !!}
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-calendar-o"></i></span>
            {!! Form::text('start_date', null, 
              ['class'=>'form-control', 'placeholder'=>'Mulai', 
              'id'=>'start_date', 'data-parsley-required'=>'true',
              'readonly' => 'readonly'])
            !!}
          </div>
          {!! $errors->first('start_date', ' <p class="help-block">:message</p>') !!}
        </div>
      </div>
      <!-- end start_date field -->

      <!-- begin day_assignment field -->
      <div class="col-xs-6">
        <div class="form-group{{ $errors->has('day_assignment') ? ' has-error' : '' }}">
          {!! Form::label('day_assignment', 'Berakhir pada') !!}
          {!! Form::select('day_assignment', [ '=' => 'Hari yang sama', '>' => 'Keesokan hari' ],
            null, ['class'=>'form-control', 'id'=>'day_assignment', 
            'data-parsley-required' => 'true', 'placeholder' => 'Silahkan pilih']); !!}
          {!! $errors->first('day_assignment', ' <p class="help-block">:message</p>') !!}
        </div>
      </div>
      <!-- end day_assignment field -->
    </div>

    <!-- begin from & to fields -->
    <div class="row">
      <div class="col-xs-6">
        <div class="form-group{{ $errors->has('from') ? ' has-error' : '' }}">
            {!! Form::label('from', 'Mulai') !!}
            <div class="input-group bootstrap-timepicker">
                {!! Form::text('from', null, 
                  ['class'=>'form-control', 'placeholder'=>'Jam mulai', 
                    'id'=>'from', 'data-provide'=>'timepicker', 
                    'data-show-meridian'=>'false',
                    'data-minute-step'=>15, 'data-default-time'=>'false',
                    'data-parsley-required'=>'true'])
                !!}
                <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
              </div>
              {!! $errors->first('from', ' <p class="help-block">:message</p>') !!}          
        </div>
      </div>
      <div class="col-xs-6">
        <div class="form-group{{ $errors->has('to') ? ' has-error' : '' }}">
            {!! Form::label('to', 'Berakhir') !!}
            <div class="input-group bootstrap-timepicker">
                {!! Form::text('to', null, 
                [ 'class'=>'form-control', 'placeholder'=>'Jam berakhir', 
                  'id'=>'to', 'data-parsley-required' => 'true',
                  'data-provide'=>'timepicker', 'data-show-meridian'=>'false',
                  'data-minute-step'=>15, 'data-default-time'=>'false',
                ]) 
                !!}
                <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
              </div>
              {!! $errors->first('to', ' <p class="help-block">:message</p>') !!}
        </div>
      </div>
    </div>
    <!-- end from & to fields -->

    <!-- begin overtime_reason_id field -->
      <div class="form-group{{ $errors->has('overtime_reason_id') ? ' has-error' : '' }}">
        {!! Form::label('overtime_reason_id', 'Alasan Lembur') !!}
          {!! Form::select('overtime_reason_id', $overtime_reason,
          null, ['class'=>'form-control', 'id'=>'overtime_reason_id', 
          'data-parsley-required' => 'true', 'placeholder' => 'Silahkan pilih']); 
          !!}
        {!! $errors->first('overtime_reason_id', ' <p class="help-block">:message</p>') !!}
      </div>
      <!-- end overtime_reason_id field -->

    <!-- begin superintendent_approver field -->
    <!-- This field is not sent via form -->
    <div class="form-group{{ $errors->has('superintendent_approver') ? ' has-error' : '' }}">
        {!! Form::label('superintendent_approver', 'Superintendent') !!}
        <select class="form-control superintendent-selectize">
            <option value="" selected>Pilih Atasan</option>
          </select>
      </div>
      <!-- end superintendent_approver field -->

      <!-- begin manager_approver field -->
    <!-- This field is not sent via form -->
    <div class="form-group{{ $errors->has('manager_approver') ? ' has-error' : '' }}">
        {!! Form::label('manager_approver', 'Manager') !!}
        <select class="form-control manager-selectize">
            <option value="" selected>Pilih Atasan</option>
          </select>
      </div>
      <!-- end manager_approver field -->

      <!-- begin submit button -->
    <div class="form-group pull-right">
      {!! Form::submit('Kirim Pengajuan Lembur', ['class'=>'btn btn-primary']) !!}
    </div>
    <!-- end submit button -->
  </div>

resources/views/overtimes/_formas.blade.php
{{--
Form Elements: personnel_no, start_date, day_assignment, from,
to, overtime_reason, delegation (if have subordinates)
--}}

<div class="col-lg-4">
    @include('layouts._flash')
    <div class="alert alert-success fade in">
      <i class="fa fa-paper-plane pull-left"></i>
      <p>Pastikan bahwa tanggal yang dipilih tidak terdapat hari libur kerja/nasional di dalam jadwal kerja Anda.</p>
      <br />
      <i class="fa fa-calendar pull-left"></i>
      <p>Silahkan isi tanggal pengajuan lembur Anda dengan memilih tanggal pada kalender.</p>
      <br />
      <i class="fa fa-clock-o pull-left"></i>
      <p>Silahkan isi keterangan apakah lembur selesai pada hari yang sama atau keesokan hari.</p>
      <br />
      <i class="fa fa-clock-o pull-left"></i>
      <p>Silahkan isi jam mulai dan berakhir lembur Anda dengan memilih jam pada icon <i class="fa fa-clock-o"></i>.</p>
      <br />
      <i class="fa fa-sliders pull-left"></i>
      <p>Silahkan isi jenis lembur Anda.</p>
      <br />
    </div>
  </div>
  
  <div class="col-lg-4">
    <!-- begin personnel_no field -->
    <div class="form-group p-l-5 p-r-5 {{ $errors->has('personnel_no') ? ' has-error' : '' }}">
      {!! Form::label('personnel_no', 'Karyawan') !!}
      {!! Form::select(
        'personnel_no',
        [],
        null,
        [
          'class'=>'form-control sub-selectize',
          'id'=>'personnel_no',
          'data-parsley-required' => 'true',
          'placeholder' => 'Silahkan pilih karyawan'
        ])
      !!}
      {!! $errors->first('personnel_no', '<p class="help-block">:message</p>') !!}
    </div>
    <!-- end personnel_no field -->
  
    <!-- begin datepicker inline -->
    <h5 class="text-center">Pilih tanggal</h5>
    <div id="datepicker-inline" class="datepicker-range">
      <div></div>
    </div>
    <!-- end datepicker inline -->
  </div>
  
  <div class="col-lg-4">
  
    <div class="row">
      <!-- begin start_date field -->
      <div class="col-xs-6">
        <div class="form-group{{ $errors->has('start_date') ? ' has-error' : '' }}">
          {!! Form::label('start_date', 'Tanggal Mulai') !!}
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-calendar-o"></i></span>
            {!! Form::text('start_date', null,
            ['class'=>'form-control', 'placeholder'=>'Mulai',
            'id'=>'start_date', 'data-parsley-required'=>'true',
            'readonly' => 'readonly'])
            !!}
          </div>
          {!! $errors->first('start_date', ' <p class="help-block">:message</p>') !!}
        </div>
      </div>
      <!-- end start_date field -->
  
      <!-- begin day_assignment field -->
      <div class="col-xs-6">
        <div class="form-group{{ $errors->has('day_assignment') ? ' has-error' : '' }}">
          {!! Form::label('day_assignment', 'Berakhir pada') !!}
          {!! Form::select('day_assignment', [ '=' => 'Hari yang sama', '>' => 'Keesokan hari' ],
          null, ['class'=>'form-control', 'id'=>'day_assignment',
          'data-parsley-required' => 'true', 'placeholder' => 'Silahkan pilih']); !!}
          {!! $errors->first('day_assignment', ' <p class="help-block">:message</p>') !!}
        </div>
      </div>
      <!-- end day_assignment field -->
    </div>
  
    <!-- begin from & to fields -->
    <div class="row">
      <div class="col-xs-6">
        <div class="form-group{{ $errors->has('from') ? ' has-error' : '' }}">
          {!! Form::label('from', 'Mulai') !!}
          <div class="input-group bootstrap-timepicker">
            {!! Form::text('from', null,
            ['class'=>'form-control', 'placeholder'=>'Jam mulai',
            'id'=>'from', 'data-provide'=>'timepicker',
            'data-show-meridian'=>'false',
            'data-minute-step'=>15, 'data-default-time'=>'false',
            'data-parsley-required'=>'true'])
            !!}
            <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
          </div>
          {!! $errors->first('from', ' <p class="help-block">:message</p>') !!}
        </div>
      </div>
      <div class="col-xs-6">
        <div class="form-group{{ $errors->has('to') ? ' has-error' : '' }}">
          {!! Form::label('to', 'Berakhir') !!}
          <div class="input-group bootstrap-timepicker">
            {!! Form::text('to', null,
            [ 'class'=>'form-control', 'placeholder'=>'Jam berakhir',
            'id'=>'to', 'data-parsley-required' => 'true',
            'data-provide'=>'timepicker', 'data-show-meridian'=>'false',
            'data-minute-step'=>15, 'data-default-time'=>'false',
            ])
            !!}
            <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
          </div>
          {!! $errors->first('to', ' <p class="help-block">:message</p>') !!}
        </div>
      </div>
    </div>
    <!-- end from & to fields -->
  
    <!-- begin overtime_reason_id field -->
    <div class="form-group{{ $errors->has('overtime_reason_id') ? ' has-error' : '' }}">
      {!! Form::label('overtime_reason_id', 'Alasan Lembur') !!}
      {!! Form::select('overtime_reason_id', $overtime_reason,
      null, ['class'=>'form-control', 'id'=>'overtime_reason_id',
      'data-parsley-required' => 'true', 'placeholder' => 'Silahkan pilih']);
      !!}
      {!! $errors->first('overtime_reason_id', ' <p class="help-block">:message</p>') !!}
    </div>
    <!-- end overtime_reason_id field -->
  
    <!-- begin superintendent_approver field -->
    <!-- This field is not sent via form -->
    <div class="form-group{{ $errors->has('superintendent_approver') ? ' has-error' : '' }}">
      {!! Form::label('superintendent_approver', 'Superintendent') !!}
      <select class="form-control superintendent-selectize">
        <option value="" selected>Pilih Superintendent</option>
      </select>
    </div>
    <!-- end superintendent_approver field -->
  
    <!-- begin manager_approver field -->
    <!-- This field is not sent via form -->
    <div class="form-group{{ $errors->has('manager_approver') ? ' has-error' : '' }}">
      {!! Form::label('manager_approver', 'Manager') !!}
      <select class="form-control manager-selectize">
        <option value="" selected>Pilih Manager</option>
      </select>
    </div>
    <!-- end manager_approver field -->
  
    <!-- begin submit button -->
    <div class="form-group pull-right">
      {!! Form::submit('Kirim Pengajuan Lembur', ['class'=>'btn btn-primary']) !!}
    </div>
    <!-- end submit button -->
  </div>

resources/views/overtimes/_summary.blade.php
<p class="pull-right">{{$when}}</p>
<p>{{$summary->employee->PersonnelNoWithName}}</p>
<p>{{$summary->attendanceQuotaType->text}} ({{$summary->duration}} menit)</p>
@component('components._stage-description', [
    'class' => $summary->stage->class_description, 
    'description' => $summary->stage->description
])
@endcomponent

resources/views/overtimes/show.blade.php
<table id="table-detail" class="table table-bordered table-condensed m-b-0" 
    data-id="{{ $overtime->plain_id }}">
    <tbody>
        <tr>
            <td>Nama</td>
        <td> {{ $overtime->employee->PersonnelNoWithName }}</td>
        </tr>
        <tr>
            <td>Mulai</td>
        <td> {{ $overtime->start_date }} </td>
        </tr>
        <tr>
            <td>Berakhir</td>
            <td> {{ $overtime->end_date }} </td>
        </tr>
        <tr>
            <td>Durasi</td>
            <td>{{ $overtime->duration }} menit</td>
        </tr>
        <tr>
            <td>Jenis Lembur</td>
            <td>{{ $overtime->overtimeReason->text }}</td>
        </tr>
        <tr>
            <td>Atasan</td>
            <td>
                @foreach ($overtime->attendanceQuotaApproval as $item)
                @component('layouts._personnel-no-with-name', [
                    'personnel_no' => $item->employee->personnel_no,
                    'employee_name' => $item->employee->name])
                @endcomponent
                <br />
                @endforeach
            </td>
        </tr>
        <tr>
            <td>Tahap</td>
            <td><span class="label label-default">{{ $overtime->stage->description }}</span></td>
        </tr>
    </tbody>
</table>